#!/bin/bash

# Script to build components needed before reboot

. ../ansicolors

boldgreen "Building 0-before_reboot"

SUBDIRS=

for i in *; do
        if [[ -d ${i} ]]; then
                SUBDIRS="${SUBDIRS} ${i}"
        else
                PROGS="${PROGS} ${i}"
        fi
done

for i in ${SUBDIRS}; do
        green "    Beginning substage ${i}"
        if [[ ! -e ${i}/.completed ]]; then
                pushd ${i}
                ./build
                rc=$?
                if [[ 0 != ${rc} ]]; then
                        red "    Substage ${i} failed"
                        exit ${rc}
                fi
                popd
        fi
        green "    Substage ${i} completed"
done

for i in ${PROGS}; do
        green "    Beginning subprogram ${i}"
        ${i}
        rc=$?
        if [[ 0 != ${rc} ]]; then
                red "    Subprogram ${i} failed"
                exit ${rc}
        fi
        green "    Subprogram ${i} completed"
done

yellow "Finished building 0-before_reboot"
