#!/bin/bash

set -e
##
# @file build
# @author Jas Eckard <jas+jasix@eckard.com>
#
# @section LICENSE
#
# (GPL license?)
#
# @section DESCRIPTION
#
# Script to automate the build of jasix:
# Create build environment by installing programs needed to build

# Return codes:  1 = bad parameter(s)
#                2 = required parameter missing

readonly localDir="$(cd ${BASH_SOURCE[0]%/*} && pwd -P && cd - >/dev/null)"

# To get some debug output call this file like:
# DEBUG=true ./build.sh ...

echoStderr() { echo "$@" 1>&2; }

if [[ 'x' == "x${DEBUG}" ]]; then
        # Make `debug' a no-op
        debug() { :; }
else
        debug() {
                echoStderr -n "DEBUG ${BASH_LINENO[*]}:  "
                echoStderr "$@"
        }
fi

# Usages:
#echo “regular stdout output”
#echoStderr “regular stderr output”
#debug “stderr output only seen when DEBUG set”

declare rc=0
readonly PROGRAMS=$(<programList)

checkIfCompleted()
{
        if [[ -e .completed ]] ; then
                echo "This step is already completed."
                exit 0
        fi
}

installPkgs()
{
        #sudo yum -y install ${PROGRAMS}
        #sudo apt update
        #sudo apt -y install ${PROGRAMS}

        if [[ 0 == $? ]]; then
                touch .completed
        fi
}  # installPkgs()

checkIfCompleted
installPkgs
