#!/bin/bash

readonly RESET="\\033[0;0m"  # White on black

readonly BLACK="\\033[0;30m"
readonly BLUE="\\033[0;34m"
readonly CYAN="\\033[0;36m"
readonly GREEN="\\033[0;32m"
readonly MAGENTA="\\033[0;35m"
readonly RED="\\033[0;31m"
readonly WHITE="\\033[0;37m"
readonly YELLOW="\\033[0;33m"

readonly BOLDBLACK="\\033[1;30m"
readonly BOLDBLUE="\\033[1;34m"
readonly BOLDCYAN="\\033[1;36m"
readonly BOLDGREEN="\\033[1;32m"
readonly BOLDMAGENTA="\\033[1;35m"
readonly BOLDRED="\\033[1;31m"
readonly BOLDWHITE="\\033[1;37m"
readonly BOLDYELLOW="\\033[1;33m"

readonly REVERSEBLACK="\\033[3;30m"
readonly REVERSEBLUE="\\033[3;34m"
readonly REVERSECYAN="\\033[3;36m"
readonly REVERSEGREEN="\\033[3;32m"
readonly REVERSEMAGENTA="\\033[3;35m"
readonly REVERSERED="\\033[3;31m"
readonly REVERSEWHITE="\\033[3;37m"
readonly REVERSEYELLOW="\\033[3;33m"

readonly UNDERLINEBLACK="\\033[4;30m"
readonly UNDERLINEBLUE="\\033[4;34m"
readonly UNDERLINECYAN="\\033[4;36m"
readonly UNDERLINEGREEN="\\033[4;32m"
readonly UNDERLINEMAGENTA="\\033[4;35m"
readonly UNDERLINERED="\\033[4;31m"
readonly UNDERLINEWHITE="\\033[4;37m"
readonly UNDERLINEYELLOW="\\033[4;33m"

black()
{
        echo -e "${BLACK}${@}${RESET}"
}  # black()

blue()
{
        echo -e "${BLUE}${@}${RESET}"
}  # blue()

cyan()
{
        echo -e "${CYAN}${@}${RESET}"
}  # cyan()

green()
{
        echo -e "${GREEN}${@}${RESET}"
}  # green()

magenta()
{
        echo -e "${MAGENTA}${@}${RESET}"
}  # magenta()

red()
{
        echo -e "${RED}${@}${RESET}"
}  # red()

white()
{
        echo -e "${WHITE}${@}${RESET}"
}  # white()

yellow()
{
        echo -e "${YELLOW}${@}${RESET}"
}  # yellow()

boldblack()
{
        echo -e "${BOLDBLACK}${@}${RESET}"
}  # boldblack()

boldblue()
{
        echo -e "${BOLDBLUE}${@}${RESET}"
}  # boldblue()

boldcyan()
{
        echo -e "${BOLDCYAN}${@}${RESET}"
}  # boldcyan()

boldgreen()
{
        echo -e "${BOLDGREEN}${@}${RESET}"
}  # boldgreen()

boldmagenta()
{
        echo -e "${BOLDMAGENTA}${@}${RESET}"
}  # boldmagenta()

boldred()
{
        echo -e "${BOLDRED}${@}${RESET}"
}  # boldred()

boldwhite()
{
        echo -e "${BOLDWHITE}${@}${RESET}"
}  # boldwhite()

boldyellow()
{
        echo -e "${BOLDYELLOW}${@}${RESET}"
}  # boldyellow()

reverseblack()
{
        echo -e "${REVERSEBLACK}${@}${RESET}"
}  # reverseblack()

reverseblue()
{
        echo -e "${REVERSEBLUE}${@}${RESET}"
}  # reverseblue()

reversecyan()
{
        echo -e "${REVERSECYAN}${@}${RESET}"
}  # reversecyan()

reversegreen()
{
        echo -e "${REVERSEGREEN}${@}${RESET}"
}  # reversegreen()

reversemagenta()
{
        echo -e "${REVERSEMAGENTA}${@}${RESET}"
}  # reversemagenta()

reversered()
{
        echo -e "${REVERSERED}${@}${RESET}"
}  # reversered()

reversewhite()
{
        echo -e "${REVERSEWHITE}${@}${RESET}"
}  # reversewhite()

reverseyellow()
{
        echo -e "${REVERSEYELLOW}${@}${RESET}"
}  # reverseyellow()

underlineblack()
{
        echo -e "${UNDERLINEBLACK}${@}${RESET}"
}  # underlineblack()

underlineblue()
{
        echo -e "${UNDERLINEBLUE}${@}${RESET}"
}  # underlineblue()

underlinecyan()
{
        echo -e "${UNDERLINECYAN}${@}${RESET}"
}  # underlinecyan()

underlinegreen()
{
        echo -e "${UNDERLINEGREEN}${@}${RESET}"
}  # underlinegreen()

underlinemagenta()
{
        echo -e "${UNDERLINEMAGENTA}${@}${RESET}"
}  # underlinemagenta()

underlinered()
{
        echo -e "${UNDERLINERED}${@}${RESET}"
}  # underlinered()

underlinewhite()
{
        echo -e "${UNDERLINEWHITE}${@}${RESET}"
}  # underlinewhite()

underlineyellow()
{
        echo -e "${UNDERLINEYELLOW}${@}${RESET}"
}  # underlineyellow()
