#!/bin/sh

set -e

# Script to automate the build of Jasix

echo "\\033[1;32m=== Building Jasix ===\\033[0;0m"

git clone https://github.com/chruck/jasix.git

cd jasix

subdirs="0-before_reboot 1-after_reboot"

for i in ${subdirs}; do
        if [ ! -e ${i}/.completed ]; then
                cd ${i}
                ./build
                cd ..
        fi
done

echo Finished building Jasix
