#!/bin/bash

##
# @file preBootstrapDebKnopKvm
# @author Jas Eckard <jas+jasix@eckard.com>
#
# @section LICENSE
#
# GPLv3
#
# @section DESCRIPTION
#
# This file is used to download Knoppix, then boot a KVM image into
# Knoppix

# Return codes:  1 = bad parameter(s)
#                2 = required parameter missing
#                3 = required program missing

readonly localDir="$(cd ${BASH_SOURCE[0]%/*} && pwd -P && cd - >/dev/null)"

# To get some debug output call this file like:
# DEBUG=true ./preBootstrapDebKnopKvm.sh ...

echoStderr() { echo "$@" 1>&2; }

if [[ 'x' == "x${DEBUG}" ]]; then
        # Make `debug' a no-op
        debug() { :; }
else
        debug() {
                echoStderr -n "DEBUG ${BASH_LINENO[*]}:  "
                echoStderr "$@"
        }
fi

declare rc=0

. ansicolors 

Usage()
{
        cat 1>&2 <<EOFUsage

Usage:  $0 [OPTION]... REQUIRED [OPTIONAL]

  -h, -?, --help        Display this help and exit

EOFUsage
        exit ${rc}
}  # Usage()

parseOptions()
{
        debug "Original args:  $@"

        local shortopts="h?" ; local longopts="help,"

        debug "shortopts=${shortopts} longopts=${longopts}"

        ARGS=$(getopt -o "${shortopts}" -l "${longopts}" -n "getopt.sh" -- "$@")

        getoptRc=$?
        if [[ 0 -ne "${getoptRc}" ]]; then
                echoStderr "ERROR:  getopt called incorrectly, rc=${getoptRc}"
                rc=1
                exit ${rc}
                # Alternatively, ($rc gets passed):
                #Usage
        fi

        eval set -- "${ARGS}"

        while true; do
                param=$1
                case "${param}" in
                        -h|-\?|--help)
                                debug "Asked for help"
                                Usage
                                ;;
                        --)
                                shift;
                                break;
                                ;;
                        *)
                                echoStderr "ERROR:  Unimplemented option: ${param}"
                                break;
                                ;;
                esac
        done

        debug "New args:  $@"

        if [[ 0 != ${rc} ]]; then
                Usage
        fi
}  # parseOptions()

# TODO:  Verify the parameters passed are valid
verifyParams()
{
        :
}  # verifyParams()

banner()
{
        boldwhite "--- ${BOLDYELLOW} Jasix ${BOLDWHITE} ---"
        boldwhite "Linux distribution scripted and customized by me, Jas"
        echo
}  # banner()

download()
{
        local url="$@"

        green "Downloading ${url}"

        if ! wget "${url}"; then
                local file=$(echo ${url} |rev |cut -d/ -f1 |rev)

                rm -f ${file}*
                sleep 1
                download "${url}"
        fi

}  # download()

dlInfoFiles()
{
        readonly urlparent="http://mirrors.sonic.net/knoppix/knoppix-dvd/"

        green "Checking if download of Knoppix necessary"
        rm -f index.html*
        download "${urlparent}"

        readonly isofile="$(grep -o 'KNOPPIX[^>]*EN.iso' index.html |sort -u |tail -n1)"
        readonly chkfile="${isofile}.sha1"

        rm -f ${chkfile}*
        download "${urlparent}/${chkfile}"
}  # dlInfoFiles()

verifyIso()
{
        if sha1sum -c "${chkfile}"; then
                return 0
        fi

        return 1
}  # verifyIso()

dlKnoppix()
{
        if [[ -f "${isofile}" ]]; then
                yellow "Knoppix DVD iso found."
                if verifyIso; then
                        return
                fi

                rm -f ${isofile}
        fi

        green "Downloading Knoppix image"
        download "${urlparent}/${isofile}"

        dlKnoppix
}  # dlKnoppix()

startKvm()
{
        local KVM="$(type -p kvm)"

        if [[ ! -e "${KVM}" ]]; then
                red "Cannot find KVM in your \$PATH"
                exit 3
        fi

        dd if=/dev/zero of=jasix.hda bs=1G count=1

        green "Starting KVM:"
        boldred "Once the VM is booted execute (optional in parentheses):"
        boldwhite "- (Start/Knoppix/Start SSH Server)"
        boldwhite "- (In Terminal Emulator:  ssh -R 2222:localhost:22 ${RED}someusername${BOLDWHITE}@\$(route |awk 'default {print \$2}') )"
        boldwhite "- (From the host:  ssh knoppix@localhost -p 2222)"
        boldwhite "- wget -O - https://raw.githubusercontent.com/chruck/jasix/master/mkJasix | sh"
        kvm -m 1G -smp 2 -cdrom ${isofile} -hda jasix.hda
}  # startKvm()

parseOptions "$@"
verifyParams
banner
dlInfoFiles
dlKnoppix
startKvm
