#!/bin/bash

##
# @file verifyEraseDevice
# @author Jas Eckard <jas+jasix@eckard.com>
#
# @section LICENSE
#
# (GPL license?)
#
# @section DESCRIPTION
#
# This file is ...

# Return codes:  1 = bad parameter(s)
#                2 = required parameter missing
#                3 = User answered "No"

readonly localDir="$(cd ${BASH_SOURCE[0]%/*} && pwd -P && cd - >/dev/null)"

# To get some debug output call this file like:
# DEBUG=true ./verifyEraseDevice ...

echoStderr() { echo "$@" 1>&2; }

if [[ 'x' == "x${DEBUG}" ]]; then
        # Make `debug' a no-op
        debug() { :; }
else
        debug() {
                echoStderr -n "DEBUG ${BASH_LINENO[*]}:  "
                echoStderr "$@"
        }
fi

# Usages:
#echo “regular stdout output”
#echoStderr “regular stderr output”
#debug “stderr output only seen when DEBUG set”

declare rc=0
declare optionA=0
declare DEVICE
declare OPTIONAL=bogus
readonly pi="3.1415"

Usage()
{
        cat 1>&2 <<EOFUsage

Usage:  $0 [OPTION]... DEVICE [OPTIONAL]

  -a, --optionA         Description
  -h, -?, --help        Display this help and exit

EOFUsage
        exit ${rc}
}  # Usage()

parseOptions()
{
        debug "Original args:  $@"

        local shortopts="h?" ; local longopts="help,"
        shortopts+="a"; longopts+="optionA,"

        debug "shortopts=${shortopts} longopts=${longopts}"

        ARGS=$(getopt -o "${shortopts}" -l "${longopts}" -n "getopt.sh" -- "$@")

        getoptRc=$?
        if [[ 0 -ne "${getoptRc}" ]]; then
                echoStderr "ERROR:  getopt called incorrectly, rc=${getoptRc}"
                rc=1
                exit ${rc}
                # Alternatively, ($rc gets passed):
                #Usage
        fi

        eval set -- "${ARGS}"

        while true; do
                param=$1
                case "${param}" in
                        -a|--optionA)
                                debug "-a used"
                                optionA=1
                                shift
                                ;;
                        -h|-\?|--help)
                                debug "Asked for help"
                                Usage
                                ;;
                        --)
                                shift;
                                break;
                                ;;
                        *)
                                echoStderr "ERROR:  Unimplemented option: ${param}"
                                break;
                                ;;
                esac
        done

        debug "New args:  $@"

        # For 1 required and one optional argument
        if [[ 1 != ${#@} && 2 != ${#@} ]]; then
                rc=2
                echoStderr "ERROR:  DEVICE required."
        fi

        DEVICE=$1
        OPTIONAL=$2

        if [[ 0 != ${rc} ]]; then
                Usage
        fi
}  # parseOptions()

# TODO:  Verify the parameters passed are valid
verifyParams()
{
        :
#       if [[ "${optionB}" =~ /reg[ex]/ ]]; then
#               echoStderr "ERROR:  --optionB should be of the form: reg[ex]"
#               rc=2
#       fi
}  # verifyParams()

verifyEraseDevice()
{
        local device=$@

        read -p "This will erase ${device}.  Are you sure? [yN] " ERASE

        if [[ "xy" != "x${ERASE}" ]]; then
                echo "User chose not to erase ${device}.  Cancelled."
                exit 3
        fi
}  # verifyEraseDevice()

parseOptions "$@"
verifyParams
verifyEraseDevice ${DEVICE}
